//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Assembly.kernel")]
[assembly: System.Reflection.AssemblyProduct("Assembly Kernel")]
[assembly: System.Reflection.AssemblyCompany("Informatiehuis Water")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2018, All rights reserved")]
[assembly: System.Reflection.AssemblyVersion("1.3.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.0.0 - snapshot")]


